-- Inventory Phase 6.3: append-only movement ledger.
--
-- Every change to on-hand inventory becomes one row in inventory_movements
-- with a signed quantity. On-hand for an item = SUM(quantity) where
-- inventory_item_id = ? and company_id = ?. No materialized totals — at
-- the scale of a single contractor's catalog (hundreds of items, tens of
-- movements per item per year), the sum-on-read is plenty fast and avoids
-- the consistency burden of a denormalized snapshot.
--
-- Movement sources:
--   received        +qty  — generated by createPoReceipt (one per receipt line with an inventory_item_id)
--   issued_to_job   -qty  — Phase 6.5 will fill this in when issue-to-job ships
--   adjustment      +/-qty — manual writes from the item detail page
--   transfer_in     +qty  — Phase 6.4 (locations) reserves these
--   transfer_out    -qty  — Phase 6.4
--
-- Reversals: when a PO receipt is undone, we insert a -qty row referencing
-- the original via reversal_of_id rather than DELETEing the original. That
-- way the ledger is genuinely append-only and the audit trail survives.
--
-- Free-text PO lines (no inventory_item_id) intentionally don't generate
-- movements. They represent cost, not stock — labor, one-off rentals,
-- inspection fees, etc.

CREATE TYPE inventory_movement_type AS ENUM (
  'received',
  'issued_to_job',
  'adjustment',
  'transfer_in',
  'transfer_out'
);

CREATE TABLE IF NOT EXISTS inventory_movements (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id            uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  inventory_item_id     uuid NOT NULL REFERENCES inventory_items(id) ON DELETE CASCADE,
  quantity              numeric(14, 4) NOT NULL,
  movement_type         inventory_movement_type NOT NULL,
  occurred_at           timestamptz NOT NULL DEFAULT now(),
  created_by_user_id    uuid REFERENCES users(id) ON DELETE SET NULL,
  notes                 text,

  -- Source refs — nullable, populated based on movement_type. SET NULL on
  -- po_receipt_line so that undoing a 6.1 receipt at the data layer can
  -- write a reversal row first, then let the cascading delete orphan the
  -- original's source link without destroying the audit trail. The SUM
  -- stays correct (original + reversal = 0) and both rows remain visible
  -- in the per-item history.
  po_receipt_line_id    uuid REFERENCES po_receipt_lines(id) ON DELETE SET NULL,
  project_id            uuid REFERENCES projects(id) ON DELETE SET NULL,
  reversal_of_id        uuid REFERENCES inventory_movements(id) ON DELETE SET NULL,

  created_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS inventory_movements_company_item_idx
  ON inventory_movements (company_id, inventory_item_id);

CREATE INDEX IF NOT EXISTS inventory_movements_po_receipt_line_idx
  ON inventory_movements (po_receipt_line_id);

CREATE INDEX IF NOT EXISTS inventory_movements_project_idx
  ON inventory_movements (project_id)
  WHERE project_id IS NOT NULL;

-- Backfill: every existing po_receipt_line with an inventory_item_id (via
-- its parent po_line) becomes a "received" movement so on-hand is correct
-- from day one. occurred_at mirrors the receipt's received_at timestamp.
-- created_by_user_id mirrors the receipt's recorder when known.
INSERT INTO inventory_movements (
  company_id,
  inventory_item_id,
  quantity,
  movement_type,
  occurred_at,
  created_by_user_id,
  notes,
  po_receipt_line_id
)
SELECT
  po.company_id,
  pol.inventory_item_id,
  prl.quantity_received,
  'received'::inventory_movement_type,
  pr.received_at,
  pr.received_by_user_id,
  'Backfilled from Phase 6.1 receipt on ' || to_char(pr.received_at, 'YYYY-MM-DD'),
  prl.id
FROM po_receipt_lines prl
JOIN purchase_order_lines pol ON pol.id = prl.po_line_id
JOIN po_receipts pr ON pr.id = prl.receipt_id
JOIN purchase_orders po ON po.id = pr.purchase_order_id
WHERE pol.inventory_item_id IS NOT NULL
  AND prl.quantity_received > 0;
