-- Roadmap P7 — intercompany mirror + reconciliation.
--
-- Each company names ONE intercompany account per partner (its net Due
-- from / Due to position — Kraken "Due from TRB", TRB "Due to Kraken").
-- The two balances should always net to zero. A journal entry that hits
-- the account in one company posts its mirror in the other: the partner's
-- intercompany account on the opposite side, offset to the partner's
-- Intercompany Clearing account (or an account picked when posting) for
-- the partner's accountant to reclassify.

CREATE TABLE IF NOT EXISTS intercompany_accounts (
  company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  partner_company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  account_id uuid NOT NULL REFERENCES accounting_accounts(id) ON DELETE CASCADE,
  clearing_account_id uuid REFERENCES accounting_accounts(id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (company_id, partner_company_id),
  CHECK (company_id <> partner_company_id)
);

-- A mirror entry records what it mirrors (the origin company + entry, or
-- the origin source document for system-posted lines whose entries are
-- regenerated by a GL rebuild).
ALTER TABLE journal_entries
  ADD COLUMN IF NOT EXISTS ic_origin_company_id uuid REFERENCES companies(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS ic_origin_entry_id uuid,
  ADD COLUMN IF NOT EXISTS ic_origin_source_type text,
  ADD COLUMN IF NOT EXISTS ic_origin_source_id uuid;
CREATE INDEX IF NOT EXISTS journal_entries_ic_origin_idx
  ON journal_entries (ic_origin_company_id, ic_origin_entry_id)
  WHERE ic_origin_company_id IS NOT NULL;

-- Kraken ↔ TRB, from the accounts already in use.
INSERT INTO intercompany_accounts (company_id, partner_company_id, account_id)
SELECT '5269d154-c749-49f0-97a7-f5e02917e1dd', '81fe6373-8027-4ae6-a516-d0914ea7116f',
       'c873b1c1-5fde-4fa9-82ae-7d48756cc5bd'
WHERE EXISTS (SELECT 1 FROM accounting_accounts WHERE id = 'c873b1c1-5fde-4fa9-82ae-7d48756cc5bd')
ON CONFLICT DO NOTHING;
INSERT INTO intercompany_accounts (company_id, partner_company_id, account_id)
SELECT '81fe6373-8027-4ae6-a516-d0914ea7116f', '5269d154-c749-49f0-97a7-f5e02917e1dd',
       'bbaa8389-ec49-4fac-81dc-e62f17dfa414'
WHERE EXISTS (SELECT 1 FROM accounting_accounts WHERE id = 'bbaa8389-ec49-4fac-81dc-e62f17dfa414')
ON CONFLICT DO NOTHING;
