'use server';

import { revalidatePath } from 'next/cache';
import { z } from 'zod';
import { getActiveCompany } from '@/lib/active-company';
import { getActiveRole } from '@/lib/active-role';
import { requireAuth } from '@/lib/auth';
import { getUserNamesByIds } from '@/lib/data/users';
import { closedPeriodMessageFor } from '@/lib/data/accounting-periods';
import {
  buildIntercompanyRecon,
  postIntercompanyMirror,
  upsertIntercompanyLink,
} from '@/lib/data/intercompany';
import { canPostInPartner } from './lib/intercompany-access';

export async function saveIntercompanyLinkAction(input: {
  partnerCompanyId: string;
  accountId: string;
  clearingAccountId: string | null;
}): Promise<{ ok: boolean; error?: string }> {
  await requireAuth();
  const role = await getActiveRole();
  if (role !== 'owner') return { ok: false, error: 'Only owners set up intercompany accounts.' };
  const parsed = z
    .object({
      partnerCompanyId: z.string().uuid(),
      accountId: z.string().uuid('Pick the intercompany account'),
      clearingAccountId: z.string().uuid().nullable(),
    })
    .safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? 'Invalid input.' };
  }
  const company = await getActiveCompany();
  if (parsed.data.partnerCompanyId === company.id) {
    return { ok: false, error: 'Pick the other company.' };
  }
  await upsertIntercompanyLink({ companyId: company.id, ...parsed.data });
  revalidatePath('/reports/intercompany');
  return { ok: true };
}

/** Post the partner-side mirror of one unmatched intercompany posting. */
export async function mirrorIntercompanyItemAction(input: {
  partnerCompanyId: string;
  entryId: string;
}): Promise<{ ok: boolean; error?: string }> {
  const user = await requireAuth();
  const role = await getActiveRole();
  if (role !== 'owner' && role !== 'accounting') {
    return { ok: false, error: 'Only owners or accounting can post intercompany entries.' };
  }
  const company = await getActiveCompany();
  if (!(await canPostInPartner(user.id, input.partnerCompanyId))) {
    return {
      ok: false,
      error: 'You need owner or accounting access in the other company to post its side.',
    };
  }
  const recon = await buildIntercompanyRecon(company.id, input.partnerCompanyId);
  if (!recon?.partnerLink) {
    return { ok: false, error: 'Set up the other company’s intercompany account first.' };
  }
  const item = recon.unmatchedMine.find((i) => i.entryId === input.entryId);
  if (!item) return { ok: false, error: 'That posting is already matched.' };
  const today = new Date().toISOString().slice(0, 10);
  const closed = await closedPeriodMessageFor(
    input.partnerCompanyId,
    [item.entryDate],
    'x',
  );
  const known = await getUserNamesByIds([user.id]);
  try {
    await postIntercompanyMirror({
      originCompanyId: company.id,
      originCompanyName: company.name,
      partnerLink: recon.partnerLink,
      originNet: item.net,
      entryDate: closed ? today : item.entryDate,
      memo: item.memo,
      // Manual entries are stable; system-posted ones are regenerated by a
      // GL rebuild, so those link by their source document instead.
      originEntryId: item.sourceType === 'manual' ? item.entryId : null,
      originSourceType: item.sourceType === 'manual' ? null : item.sourceType,
      originSourceId: item.sourceType === 'manual' ? null : item.sourceId,
      createdByUserId: known.has(user.id) ? user.id : null,
    });
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : 'Could not post.' };
  }
  revalidatePath('/reports/intercompany');
  return { ok: true };
}
